### PR TITLE
 Fixed - ModuleNotFoundError: No module named 'solrSource' #19

### PR DESCRIPTION
**Pull request by atarora**

### CODE REVIEW

**Comment by atarora** [comment]
Also to add here :

The run command should have http:// added to it as well as 

> solr-to-es http://localhost:8983/solr/<<collection_name>> http://localhost:9200 <<collection_name>> solr_docs

**Comment by epugh** [comment]
can you update the README then and I'll merge this great PR!   Thanks!

**Comment by atarora** [comment]
Done

**Comment by epugh** [comment]
Thank you!

**Pull request merged**
